### ISSUE TITLE
Tests failing on master from VS 2017 Test Explorer

### ISSUE THREAD

**Issue by dcuccia** [VirtualPhotonics/VTS#9] opened 2018-09-03 20:41 UTC
Not sure, but I think this is an issue related to test framework tooling. A large number of tests in Vts.Desktop.Test (perhaps those that rely on serialization?) are failing when I use the built-in test framework of Visual Studio 2017 (15.8.1) Pro on Windows 10 Pro x64. This is on a new checkout of the repo, nothing special. See attached image:

![vts failing tests oob](https://user-images.githubusercontent.com/479617/45000934-a3485700-af7d-11e8-8b05-7f8010f5779d.PNG)

When I run the batch file (DesktopTests.bat) from the command-line, everything's hunky dory. Here's the XML data:

testcasecount="467" result="Skipped" label="Ignored" total="467" passed="444" failed="0" inconclusive="0" skipped="23" asserts="1537460" engine-version="3.8.0.0" clr-version="4.0.30319.42000"

Perhaps there's a difference in how VS Test Explorer deals with sandboxing and file artifacts? I was pretty sure this is still using NUnit under the hood, but I could be wrong. Not sure what to do next, so posting to see if anyone else has tried this and had problems.

**Comment by hayakawa16** [comment] 2018-09-04 01:03
Hi dcuccia,  

I am very sorry you're experiencing this!  Typically when our code is pushed to Github all unit tests pass. I am using VS 2017 (15.8.1) as well and am finding 4 errors.  I thought possibly it was due to your using the Text Explorer (which uses Test Runner I think), but I ran the tests using the Text Explorer and Nunit and I get the same 4 errors in both:
<img width="960" alt="myerrors" src="https://user-images.githubusercontent.com/26939347/45004483-eb797080-afa1-11e8-8852-bad612b196a7.PNG">

I'm not sure why you're experiencing more errors.  I too ran BuildTestRelease.bat and all worked fine so I was relieved for that.  The errors I'm finding have to do with reading the SpectralDatabase and in particular reading in the data from the file Spectroscopy/Resources/Spectra.txt.  It reads the header of the file successfully but on the first line of data it reads with the code:
var valEntry = convert ? Convert.ToDouble(row[i+1]).ConvertCoefficient(chromophoreList[i].AbsorptionCoefficientUnit, chromophoreList[i].MolarUnit) : Convert.ToDouble(row[i+1]);
                                
the code excepts with an error saying the data is not in the correct format.  It could be due to the removal of Automapper from our solution.  I tried adding the package back in, but this did not solve the problem.

I'll keep debugging my 4 errors and hopefully by solving them, we might have a clue about the 70 additional errors you're encountering.

**Comment by lmalenfant** [comment] 2018-09-05 02:58
I just pulled a clean clone and added the Microsoft.NET.Test.Sdk NuGet package back in because it was still being used. All unit tests pass when I run them from both Resharper and Test Explorer.

The only difference I can see is that my version of Visual Studio is 15.6.7, I will update to 15.8.2 and see if this changes anything.

**Comment by hayakawa16** [comment] 2018-09-05 22:07
I updated to 15.8.2 and still had 4 unit tests failing.  Then lmalenfant suggested that I revert my laptop to English.  I had set it to French to use our WPF GUI in french.  When I rebooted in English and ran the unit tests, all pass now.

**Comment by dcuccia** [comment] 2018-09-05 23:43
Haha, c'est bon ! Thanks - will see if I can repro on another machine.

**Comment by hayakawa16** [comment] 2018-09-19 23:01
Just curious as to whether dcuccia was able to reproduce the failing unit tests on another machine.

**Comment by hayakawa16** [comment] 2018-09-26 21:11
If we are not informed of way to reproduce this issue, we plan to close it in a week.  Thanks.

**Comment by dcuccia** [comment] 2018-09-27 04:31
Carole, thanks for checking up. Yes, just did a fresh check-out and ran
unit tests and they were all passing. Must have been a fluke. OK to close.
-David

>

**Comment by hayakawa16** [comment] 2018-09-27 14:56
Thanks for letting me know.  Good to hear there isn't a problem.

**Closed by hayakawa16** 2018-09-27 14:56 UTC
